version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
    commit-message:
      prefix: ðŸ‘·
    labels: [github-actions, dependencies]
  - package-ecosystem: gomod
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
    commit-message:
      prefix: â¬†
    labels: [go, dependencies]
